-- ===============================================
-- Usalingo データベーススキーマ テーブル作成
-- ===============================================
-- 目的: 最新の要件定義書に基づいて新しいテーブルを作成する

-- ===============================================
-- Tier 1: Words (親)
-- ===============================================
CREATE TABLE public.words (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_text TEXT NOT NULL UNIQUE
);

-- ===============================================
-- Tier 2: Meanings (子)
-- ===============================================
CREATE TABLE public.word_meanings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id INTEGER NOT NULL REFERENCES public.words(id) ON DELETE CASCADE,
    priority INTEGER NOT NULL DEFAULT 1,
    part_of_speech_en TEXT NOT NULL,
    part_of_speech_jp TEXT,
    definition_jp TEXT NOT NULL,
    cefr_level TEXT,
    etymology TEXT,
    synonyms TEXT[],
    antonyms TEXT[],
    pronunciation_ipa TEXT,
    pronunciation_kana TEXT,
    pronunciation_cmu TEXT,
    audio_url TEXT,
    audio_asset_path TEXT,
    inflections JSONB,
    derivatives JSONB,
    collocations JSONB,
    related_phrases JSONB
);

-- ===============================================
-- Tier 3: Examples (孫)
-- ===============================================
CREATE TABLE public.example_contents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meaning_id INTEGER NOT NULL REFERENCES public.word_meanings(id) ON DELETE CASCADE,
    theme TEXT NOT NULL DEFAULT 'simple',
    sentence_en TEXT NOT NULL,
    sentence_jp TEXT NOT NULL,
    illustration_url TEXT,
    illustration_asset_path TEXT,
    audio_url TEXT,
    audio_asset_path TEXT
);

-- ===============================================
-- デッキ関連テーブル
-- ===============================================
CREATE TABLE public.decks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_name TEXT NOT NULL UNIQUE,
    description TEXT,
    source_list_name TEXT,
    license TEXT
);

-- デッキと単語の多対多関係の中間テーブル
CREATE TABLE public.deck_words (
    deck_id INTEGER NOT NULL REFERENCES public.decks(id) ON DELETE CASCADE,
    word_id INTEGER NOT NULL REFERENCES public.words(id) ON DELETE CASCADE,
    PRIMARY KEY (deck_id, word_id)
);

-- ===============================================
-- カードテンプレートテーブル
-- ===============================================
CREATE TABLE public.card_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name TEXT NOT NULL UNIQUE,
    surface_a_items TEXT[] NOT NULL,
    surface_b_items TEXT[] NOT NULL
);

-- テーブル作成完了の確認メッセージ
SELECT 'Schema creation completed successfully. All content-related tables have been created.' as status;
