-- ===============================================
-- Usalingo データベーススキーマ テーブル作成
-- ===============================================
-- 目的: 最新の要件定義書に基づいて新しいテーブルを作成する

-- ===============================================
-- Tier 1: Words (親)
-- ===============================================
CREATE TABLE public.words (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_text TEXT NOT NULL UNIQUE
);

-- ===============================================
-- Tier 2: Meanings (子)
-- ===============================================
CREATE TABLE public.word_meanings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id INTEGER NOT NULL REFERENCES public.words(id) ON DELETE CASCADE,
    priority INTEGER NOT NULL DEFAULT 1,
    part_of_speech_en TEXT NOT NULL,
    part_of_speech_jp TEXT,
    definition_jp TEXT NOT NULL,
    cefr_level TEXT,
    etymology TEXT,
    synonyms TEXT[],
    antonyms TEXT[],
    pronunciation_ipa TEXT,
    pronunciation_kana TEXT,
    pronunciation_cmu TEXT,
    audio_url TEXT,
    audio_asset_path TEXT,
    inflections JSONB,
    derivatives JSONB,
    collocations JSONB,
    related_phrases JSONB
);

-- ===============================================
-- Tier 3: Examples (孫)
-- ===============================================
CREATE TABLE public.example_contents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meaning_id INTEGER NOT NULL REFERENCES public.word_meanings(id) ON DELETE CASCADE,
    theme TEXT NOT NULL DEFAULT 'simple',
    sentence_en TEXT NOT NULL,
    sentence_jp TEXT NOT NULL,
    illustration_url TEXT,
    illustration_asset_path TEXT,
    audio_url TEXT,
    audio_asset_path TEXT
);

-- ===============================================
-- デッキ関連テーブル
-- ===============================================
CREATE TABLE public.decks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_name TEXT NOT NULL UNIQUE,
    description TEXT,
    source_list_name TEXT,
    license TEXT
);

-- デッキと単語の多対多関係の中間テーブル
CREATE TABLE public.deck_words (
    deck_id INTEGER NOT NULL REFERENCES public.decks(id) ON DELETE CASCADE,
    word_id INTEGER NOT NULL REFERENCES public.words(id) ON DELETE CASCADE,
    PRIMARY KEY (deck_id, word_id)
);

-- ===============================================
-- カードテンプレートテーブル
-- ===============================================
CREATE TABLE public.card_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name TEXT NOT NULL UNIQUE,
    surface_a_items TEXT[] NOT NULL,
    surface_b_items TEXT[] NOT NULL
);

-- テーブル作成完了の確認メッセージ
SELECT 'Schema creation completed successfully. All content-related tables have been created.' as status;
-- ===============================================
-- Usalingo データベーススキーマ インデックス作成
-- ===============================================
-- 目的: クエリのパフォーマンスを向上させるためのインデックスを作成する

-- word_meaningsテーブルのインデックス
CREATE INDEX IF NOT EXISTS idx_meanings_on_word_id 
ON public.word_meanings (word_id);

-- 例文コンテンツテーブルのインデックス
CREATE INDEX IF NOT EXISTS idx_examples_on_meaning_id 
ON public.example_contents (meaning_id);

-- デッキ単語中間テーブルのインデックス
CREATE INDEX IF NOT EXISTS idx_deck_words_on_deck_id 
ON public.deck_words (deck_id);

CREATE INDEX IF NOT EXISTS idx_deck_words_on_word_id 
ON public.deck_words (word_id);

-- インデックス作成完了の確認メッセージ
SELECT 'Indexes creation completed successfully. All performance indexes have been created.' as status;
-- ===============================================
-- Usalingo データベーススキーマ RLSポリシー設定
-- ===============================================
-- 目的: テーブルへのアクセスを制御するRow Level Security (RLS) を設定する

-- ===============================================
-- RLS有効化
-- ===============================================
ALTER TABLE public.words ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.word_meanings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.example_contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.decks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deck_words ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_templates ENABLE ROW LEVEL SECURITY;

-- ===============================================
-- 公開データポリシー（誰でも読み取り可能）
-- ===============================================

-- wordsテーブル: 全てのユーザーが読み取り可能
CREATE POLICY "words_select_policy" ON public.words
    FOR SELECT USING (true);

-- word_meaningsテーブル: 全てのユーザーが読み取り可能
CREATE POLICY "word_meanings_select_policy" ON public.word_meanings
    FOR SELECT USING (true);

-- example_contentsテーブル: 全てのユーザーが読み取り可能
CREATE POLICY "example_contents_select_policy" ON public.example_contents
    FOR SELECT USING (true);

-- decksテーブル: 全てのユーザーが読み取り可能
CREATE POLICY "decks_select_policy" ON public.decks
    FOR SELECT USING (true);

-- deck_wordsテーブル: 全てのユーザーが読み取り可能
CREATE POLICY "deck_words_select_policy" ON public.deck_words
    FOR SELECT USING (true);

-- card_templatesテーブル: 全てのユーザーが読み取り可能
CREATE POLICY "card_templates_select_policy" ON public.card_templates
    FOR SELECT USING (true);

-- ===============================================
-- 書き込み制限ポリシー（管理者のみ）
-- ===============================================

-- wordsテーブル: 書き込みは管理者のみ（現在は制限）
CREATE POLICY "words_insert_policy" ON public.words
    FOR INSERT WITH CHECK (false);

CREATE POLICY "words_update_policy" ON public.words
    FOR UPDATE USING (false);

CREATE POLICY "words_delete_policy" ON public.words
    FOR DELETE USING (false);

-- word_meaningsテーブル: 書き込みは管理者のみ
CREATE POLICY "word_meanings_insert_policy" ON public.word_meanings
    FOR INSERT WITH CHECK (false);

CREATE POLICY "word_meanings_update_policy" ON public.word_meanings
    FOR UPDATE USING (false);

CREATE POLICY "word_meanings_delete_policy" ON public.word_meanings
    FOR DELETE USING (false);

-- example_contentsテーブル: 書き込みは管理者のみ
CREATE POLICY "example_contents_insert_policy" ON public.example_contents
    FOR INSERT WITH CHECK (false);

CREATE POLICY "example_contents_update_policy" ON public.example_contents
    FOR UPDATE USING (false);

CREATE POLICY "example_contents_delete_policy" ON public.example_contents
    FOR DELETE USING (false);

-- decksテーブル: 書き込みは管理者のみ
CREATE POLICY "decks_insert_policy" ON public.decks
    FOR INSERT WITH CHECK (false);

CREATE POLICY "decks_update_policy" ON public.decks
    FOR UPDATE USING (false);

CREATE POLICY "decks_delete_policy" ON public.decks
    FOR DELETE USING (false);

-- deck_wordsテーブル: 書き込みは管理者のみ
CREATE POLICY "deck_words_insert_policy" ON public.deck_words
    FOR INSERT WITH CHECK (false);

CREATE POLICY "deck_words_update_policy" ON public.deck_words
    FOR UPDATE USING (false);

CREATE POLICY "deck_words_delete_policy" ON public.deck_words
    FOR DELETE USING (false);

-- card_templatesテーブル: 書き込みは管理者のみ
CREATE POLICY "card_templates_insert_policy" ON public.card_templates
    FOR INSERT WITH CHECK (false);

CREATE POLICY "card_templates_update_policy" ON public.card_templates
    FOR UPDATE USING (false);

CREATE POLICY "card_templates_delete_policy" ON public.card_templates
    FOR DELETE USING (false);

-- RLSポリシー設定完了の確認メッセージ
SELECT 'RLS policies setup completed successfully. All security policies have been configured.' as status;
