-- Align the delivered content schema with docs/content/source-database-v5.md.
-- This is additive: current SwiftUI compatibility columns remain available.

begin;

set local lock_timeout = '5s';
set local statement_timeout = '60s';

alter table public.words
  add column source_note_guid text,
  add column source_deck_code text,
  add column source_position integer,
  add constraint words_source_note_guid_not_blank
    check (source_note_guid is null or length(btrim(source_note_guid)) > 0),
  add constraint words_source_deck_code_not_blank
    check (source_deck_code is null or length(btrim(source_deck_code)) > 0),
  add constraint words_source_position_positive
    check (source_position is null or source_position > 0),
  add constraint words_source_position_requires_deck
    check (source_position is null or source_deck_code is not null);

create unique index words_source_note_guid_key
  on public.words (source_note_guid) where source_note_guid is not null;
create unique index words_source_deck_position_key
  on public.words (source_deck_code, source_position)
  where source_deck_code is not null and source_position is not null;

create table public.content_concepts (
  id integer generated by default as identity primary key,
  concept_code text not null unique,
  concept_name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint content_concepts_code_format
    check (concept_code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  constraint content_concepts_name_not_blank
    check (length(btrim(concept_name)) > 0)
);

insert into public.content_concepts (concept_code, concept_name, description)
values ('simple', 'シンプル', '標準の例文・画像コンセプト')
on conflict (concept_code) do nothing;

alter table public.example_contents
  add column concept_id integer,
  add column image_state text,
  add column display_order integer;

update public.example_contents as example
set concept_id = concept.id,
    image_state = case when example.image_asset_path is null then 'blank' else 'present' end,
    display_order = 1
from public.content_concepts as concept
where concept.concept_code = case
  when coalesce(nullif(example.theme, ''), 'simple') in ('simple', 'シンプル')
    then 'simple'
  else example.theme
end;

create function public.set_example_content_v5_defaults()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if new.concept_id is null
     or (
       tg_op = 'UPDATE'
       and new.theme is distinct from old.theme
       and new.concept_id is not distinct from old.concept_id
     ) then
    select id into new.concept_id
    from public.content_concepts
    where concept_code = case
      when coalesce(nullif(new.theme, ''), 'simple') in ('simple', 'シンプル')
        then 'simple'
      else new.theme
    end;
  end if;

  if new.concept_id is null then
    raise exception 'V5 example write stopped: theme has no content_concepts row.';
  end if;

  if tg_op = 'INSERT'
     or new.image_state is null
     or (
       new.image_asset_path is distinct from old.image_asset_path
       and new.image_state is not distinct from old.image_state
     ) then
    new.image_state := case
      when new.image_asset_path is null then 'blank'
      else 'present'
    end;
  end if;
  new.display_order := coalesce(new.display_order, 1);
  return new;
end;
$$;

revoke all on function public.set_example_content_v5_defaults()
  from public, anon, authenticated;

create trigger set_example_content_v5_defaults
  before insert or update on public.example_contents
  for each row execute function public.set_example_content_v5_defaults();

do $$
begin
  if exists (select 1 from public.example_contents where concept_id is null) then
    raise exception 'V5 alignment stopped: an example theme has no content_concepts row.';
  end if;
end
$$;

alter table public.example_contents
  alter column concept_id set not null,
  alter column image_state set not null,
  alter column display_order set not null,
  alter column image_state set default 'blank',
  alter column display_order set default 1,
  add constraint example_contents_concept_id_fkey
    foreign key (concept_id) references public.content_concepts(id) on delete restrict,
  add constraint example_contents_image_state_allowed
    check (image_state in ('present', 'blank', 'not_applicable', 'unverified')),
  add constraint example_contents_image_state_matches_path
    check ((image_state in ('present', 'unverified') and image_asset_path is not null)
      or (image_state in ('blank', 'not_applicable') and image_asset_path is null)),
  add constraint example_contents_display_order_positive check (display_order > 0);

create index example_contents_concept_id_idx
  on public.example_contents (concept_id, id);

create table public.word_pronunciations (
  id integer generated by default as identity primary key,
  word_id integer not null references public.words(id) on delete cascade,
  accent text not null default 'unspecified',
  ipa text,
  ipa_state text not null default 'blank',
  audio_asset_path text,
  audio_state text not null default 'blank',
  voice_label text not null default 'default',
  is_primary boolean not null default false,
  display_order integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint word_pronunciations_accent_not_blank check (length(btrim(accent)) > 0),
  constraint word_pronunciations_ipa_state_allowed
    check (ipa_state in ('present', 'blank', 'not_applicable', 'unverified')),
  constraint word_pronunciations_audio_state_allowed
    check (audio_state in ('present', 'blank', 'not_applicable', 'unverified')),
  constraint word_pronunciations_ipa_state_matches_value
    check ((ipa_state in ('present', 'unverified') and ipa is not null)
      or (ipa_state in ('blank', 'not_applicable') and ipa is null)),
  constraint word_pronunciations_audio_state_matches_path
    check ((audio_state in ('present', 'unverified') and audio_asset_path is not null)
      or (audio_state in ('blank', 'not_applicable') and audio_asset_path is null)),
  constraint word_pronunciations_voice_label_not_blank
    check (length(btrim(voice_label)) > 0),
  constraint word_pronunciations_display_order_positive check (display_order > 0)
);

create index word_pronunciations_word_order_idx
  on public.word_pronunciations (word_id, display_order, id);
create unique index word_pronunciations_one_primary_per_word
  on public.word_pronunciations (word_id) where is_primary;

insert into public.word_pronunciations (
  word_id, accent, ipa, ipa_state, audio_asset_path, audio_state,
  voice_label, is_primary, display_order
)
select meaning.word_id, 'unspecified', nullif(meaning.pronunciation_ipa, ''),
  case when nullif(meaning.pronunciation_ipa, '') is null then 'blank' else 'present' end,
  nullif(meaning.audio_asset_path, ''),
  case when nullif(meaning.audio_asset_path, '') is null then 'blank' else 'present' end,
  'default', true, 1
from (
  select distinct on (word_id) * from public.word_meanings
  order by word_id, priority, id
) as meaning
where meaning.pronunciation_ipa is not null or meaning.audio_asset_path is not null;

create table public.example_audio (
  id integer generated by default as identity primary key,
  example_id integer not null references public.example_contents(id) on delete cascade,
  audio_asset_path text,
  audio_state text not null default 'blank',
  voice_label text not null default 'default',
  is_primary boolean not null default false,
  display_order integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint example_audio_state_allowed
    check (audio_state in ('present', 'blank', 'not_applicable', 'unverified')),
  constraint example_audio_state_matches_path
    check ((audio_state in ('present', 'unverified') and audio_asset_path is not null)
      or (audio_state in ('blank', 'not_applicable') and audio_asset_path is null)),
  constraint example_audio_voice_label_not_blank check (length(btrim(voice_label)) > 0),
  constraint example_audio_display_order_positive check (display_order > 0)
);

create index example_audio_example_order_idx
  on public.example_audio (example_id, display_order, id);
create unique index example_audio_one_primary_per_example
  on public.example_audio (example_id) where is_primary;

insert into public.example_audio (
  example_id, audio_asset_path, audio_state, voice_label, is_primary, display_order
)
select id, audio_asset_path, 'present', 'default', true, 1
from public.example_contents where audio_asset_path is not null;

create table public.word_forms (
  word_id integer primary key references public.words(id) on delete cascade,
  forms_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint word_forms_json_object check (jsonb_typeof(forms_json) = 'object')
);

insert into public.word_forms (word_id, forms_json)
select distinct on (word_id) word_id, inflections
from public.word_meanings where inflections is not null
order by word_id, priority, id;

create table public.word_relations (
  word_id integer primary key references public.words(id) on delete cascade,
  relations_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint word_relations_json_object check (jsonb_typeof(relations_json) = 'object')
);

insert into public.word_relations (word_id, relations_json)
select meaning.word_id,
  jsonb_strip_nulls(jsonb_build_object(
    'synonyms', to_jsonb(meaning.synonyms), 'antonyms', to_jsonb(meaning.antonyms),
    'derivatives', meaning.derivatives, 'collocations', meaning.collocations,
    'related_phrases', meaning.related_phrases))
from (
  select distinct on (word_id) * from public.word_meanings
  order by word_id, priority, id
) as meaning
where meaning.synonyms is not null or meaning.antonyms is not null
  or meaning.derivatives is not null or meaning.collocations is not null
  or meaning.related_phrases is not null;

create trigger update_content_concepts_updated_at before update on public.content_concepts
  for each row execute function public.update_updated_at_column();
create trigger update_word_pronunciations_updated_at before update on public.word_pronunciations
  for each row execute function public.update_updated_at_column();
create trigger update_example_audio_updated_at before update on public.example_audio
  for each row execute function public.update_updated_at_column();
create trigger update_word_forms_updated_at before update on public.word_forms
  for each row execute function public.update_updated_at_column();
create trigger update_word_relations_updated_at before update on public.word_relations
  for each row execute function public.update_updated_at_column();

alter table public.content_concepts enable row level security;
alter table public.word_pronunciations enable row level security;
alter table public.example_audio enable row level security;
alter table public.word_forms enable row level security;
alter table public.word_relations enable row level security;

create policy content_concepts_select_authenticated
  on public.content_concepts for select to authenticated using (true);
create policy word_pronunciations_select_authenticated
  on public.word_pronunciations for select to authenticated using (true);
create policy example_audio_select_authenticated
  on public.example_audio for select to authenticated using (true);
create policy word_forms_select_authenticated
  on public.word_forms for select to authenticated using (true);
create policy word_relations_select_authenticated
  on public.word_relations for select to authenticated using (true);

revoke all on table public.content_concepts, public.word_pronunciations,
  public.example_audio, public.word_forms, public.word_relations
  from public, anon, authenticated;
revoke all on sequence public.content_concepts_id_seq,
  public.word_pronunciations_id_seq, public.example_audio_id_seq
  from public, anon, authenticated;

grant select on table public.content_concepts, public.word_pronunciations,
  public.example_audio, public.word_forms, public.word_relations to authenticated;
grant select, insert, update, delete on table public.content_concepts,
  public.word_pronunciations, public.example_audio, public.word_forms,
  public.word_relations to service_role;
grant usage, select on sequence public.content_concepts_id_seq,
  public.word_pronunciations_id_seq, public.example_audio_id_seq to service_role;

comment on column public.words.source_note_guid is
  'Stable source-note identifier, such as the Anki note GUID.';
comment on column public.words.source_deck_code is
  'Stable operator-defined code for the source deck.';
comment on column public.words.source_position is
  'One-based source order; never use mutable Anki review due order.';
comment on table public.content_concepts is
  'Operator-managed example and media concepts from the V5 source database.';
comment on table public.word_pronunciations is
  'Zero or more pronunciations and word-audio assets for one canonical word.';
comment on table public.example_audio is
  'Zero or more audio assets for one example sentence.';
comment on table public.word_forms is
  'Operator-managed word forms stored as one JSON object per word.';
comment on table public.word_relations is
  'Operator-managed word relations stored as one JSON object per word.';

do $$
declare target_table text;
begin
  if (select count(*) from public.content_concepts where concept_code = 'simple') <> 1 then
    raise exception 'V5 alignment verification failed: simple concept is missing.';
  end if;
  if exists (select 1 from public.example_contents
    where concept_id is null or image_state is null or display_order is null) then
    raise exception 'V5 alignment verification failed: an example row was not backfilled.';
  end if;
  foreach target_table in array array['content_concepts','word_pronunciations',
    'example_audio','word_forms','word_relations'] loop
    if has_table_privilege('anon', format('public.%I', target_table), 'select')
      or not has_table_privilege('authenticated', format('public.%I', target_table), 'select')
      or has_table_privilege('authenticated', format('public.%I', target_table), 'insert')
      or has_table_privilege('authenticated', format('public.%I', target_table), 'update')
      or has_table_privilege('authenticated', format('public.%I', target_table), 'delete')
      or not has_table_privilege('service_role', format('public.%I', target_table), 'select')
      or not has_table_privilege('service_role', format('public.%I', target_table), 'insert')
      or not has_table_privilege('service_role', format('public.%I', target_table), 'update')
      or not has_table_privilege('service_role', format('public.%I', target_table), 'delete') then
      raise exception 'V5 alignment verification failed: grants for % are incorrect.', target_table;
    end if;
  end loop;
end
$$;

commit;
