-- Reconstruct the schema required by the current SwiftUI app from an empty
-- local Supabase database. This baseline intentionally contains no production
-- data and must run before every historical incremental migration.

begin;

set local lock_timeout = '5s';
set local statement_timeout = '60s';

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.update_updated_at_column() from public, anon, authenticated;

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);

create table public.user_profiles (
  user_id uuid primary key references public.users(id) on delete cascade,
  plan text not null default 'free',
  nickname text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_profiles_plan_allowed check (plan in ('free', 'pro'))
);

create table public.words (
  id integer generated by default as identity primary key,
  word_text text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.word_meanings (
  id integer generated by default as identity primary key,
  word_id integer not null references public.words(id) on delete cascade,
  priority integer not null default 1,
  part_of_speech_en text not null,
  part_of_speech_jp text,
  definition_jp text not null,
  cefr_level text,
  etymology text,
  synonyms text[],
  antonyms text[],
  pronunciation_ipa text,
  pronunciation_kana text,
  pronunciation_cmu text,
  audio_url text,
  audio_asset_path text,
  inflections jsonb,
  derivatives jsonb,
  collocations jsonb,
  related_phrases jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint word_meanings_priority_positive check (priority > 0)
);

create table public.example_contents (
  id integer generated by default as identity primary key,
  meaning_id integer not null references public.word_meanings(id) on delete cascade,
  theme text not null default 'simple',
  sentence_en text not null,
  sentence_jp text not null,
  image_asset_path text,
  audio_asset_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.decks (
  id integer generated by default as identity primary key,
  deck_name text not null unique,
  description text,
  source_list_name text,
  license text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.deck_words (
  deck_id integer not null references public.decks(id) on delete cascade,
  word_id integer not null references public.words(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (deck_id, word_id)
);

create table public.card_templates (
  id integer generated by default as identity primary key,
  template_name text not null unique,
  surface_a_items text[] not null,
  surface_b_items text[] not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_learning_progress (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  word_id integer not null references public.words(id) on delete restrict,
  status text not null default 'learning',
  last_reviewed_at timestamptz,
  next_review_date timestamptz not null default now(),
  srs_level integer not null default 1,
  easiness_factor real not null default 2.5,
  repetitions integer not null default 0,
  interval_days integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_learning_progress_user_word_key unique (user_id, word_id),
  constraint user_learning_progress_status_allowed
    check (status in ('learning', 'review', 'mastered')),
  constraint user_learning_progress_srs_level_range check (srs_level between 1 and 5),
  constraint user_learning_progress_easiness_factor_minimum check (easiness_factor >= 1.3),
  constraint user_learning_progress_repetitions_nonnegative check (repetitions >= 0),
  constraint user_learning_progress_interval_days_nonnegative check (interval_days >= 0)
);

create index word_meanings_word_priority_idx
  on public.word_meanings (word_id, priority, id);
create index example_contents_meaning_theme_idx
  on public.example_contents (meaning_id, theme, id);
create index deck_words_word_id_idx
  on public.deck_words (word_id, deck_id);
create index user_learning_progress_due_idx
  on public.user_learning_progress (user_id, next_review_date, word_id);

create trigger update_user_profiles_updated_at
  before update on public.user_profiles
  for each row execute function public.update_updated_at_column();
create trigger update_words_updated_at
  before update on public.words
  for each row execute function public.update_updated_at_column();
create trigger update_word_meanings_updated_at
  before update on public.word_meanings
  for each row execute function public.update_updated_at_column();
create trigger update_example_contents_updated_at
  before update on public.example_contents
  for each row execute function public.update_updated_at_column();
create trigger update_decks_updated_at
  before update on public.decks
  for each row execute function public.update_updated_at_column();
create trigger update_card_templates_updated_at
  before update on public.card_templates
  for each row execute function public.update_updated_at_column();
create trigger update_user_learning_progress_updated_at
  before update on public.user_learning_progress
  for each row execute function public.update_updated_at_column();

alter table public.users enable row level security;
alter table public.user_profiles enable row level security;
alter table public.words enable row level security;
alter table public.word_meanings enable row level security;
alter table public.example_contents enable row level security;
alter table public.decks enable row level security;
alter table public.deck_words enable row level security;
alter table public.card_templates enable row level security;
alter table public.user_learning_progress enable row level security;

create policy users_select_own
  on public.users for select to authenticated
  using ((select auth.uid()) = id);

create policy user_profiles_select_own
  on public.user_profiles for select to authenticated
  using ((select auth.uid()) = user_id);
create policy user_profiles_insert_own
  on public.user_profiles for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy user_profiles_update_own
  on public.user_profiles for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy words_select_policy
  on public.words for select to authenticated using (true);
create policy word_meanings_select_policy
  on public.word_meanings for select to authenticated using (true);
create policy example_contents_select_policy
  on public.example_contents for select to authenticated using (true);
create policy decks_select_policy
  on public.decks for select to authenticated using (true);
create policy deck_words_select_policy
  on public.deck_words for select to authenticated using (true);
create policy card_templates_select_policy
  on public.card_templates for select to authenticated using (true);

create policy user_learning_progress_select_own
  on public.user_learning_progress for select to authenticated
  using ((select auth.uid()) = user_id);
create policy user_learning_progress_insert_own
  on public.user_learning_progress for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy user_learning_progress_update_own
  on public.user_learning_progress for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

revoke all on table public.users from public, anon, authenticated;
revoke all on table public.user_profiles from public, anon, authenticated;
revoke all on table public.words from public, anon, authenticated;
revoke all on table public.word_meanings from public, anon, authenticated;
revoke all on table public.example_contents from public, anon, authenticated;
revoke all on table public.decks from public, anon, authenticated;
revoke all on table public.deck_words from public, anon, authenticated;
revoke all on table public.card_templates from public, anon, authenticated;
revoke all on table public.user_learning_progress from public, anon, authenticated;

grant select on table public.users to authenticated;
grant select, insert, update on table public.user_profiles to authenticated;
grant select on table public.words to authenticated;
grant select on table public.word_meanings to authenticated;
grant select on table public.example_contents to authenticated;
grant select on table public.decks to authenticated;
grant select on table public.deck_words to authenticated;
grant select on table public.card_templates to authenticated;
grant select, insert, update on table public.user_learning_progress to authenticated;

grant select, insert, update, delete on table public.users to service_role;
grant select, insert, update, delete on table public.user_profiles to service_role;
grant select, insert, update, delete on table public.words to service_role;
grant select, insert, update, delete on table public.word_meanings to service_role;
grant select, insert, update, delete on table public.example_contents to service_role;
grant select, insert, update, delete on table public.decks to service_role;
grant select, insert, update, delete on table public.deck_words to service_role;
grant select, insert, update, delete on table public.card_templates to service_role;
grant select, insert, update, delete on table public.user_learning_progress to service_role;

grant usage, select on all sequences in schema public to service_role;

commit;
